version: "3.7"

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db-siriusfinis
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=siriusfinisdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
